### ISSUE TITLE
请问单元测试用的工具是什么？

### ISSUE THREAD

**Issue by bennyyip** [fool2fish/the-c-programming-language-exercise-answers#3]
你好，沉鱼姐姐。我是C初学者，在看K&R C自学，这个repo对我帮助很大。
我想知道单元测试是用什么工具THX

**Comment by fool2fish** [comment]
没有特别用什么工具，这些习题的输出运行一遍一眼就看的出来对不对啊

On Thu, Sep 10, 2015 at 5:03 AM, BenYip notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/fool2fish/the-c-programming-language-exercise-answers/issues/3
> .

## 

《挨踢民工日志》四格漫画连载中
fool2fish.cn

**Comment by bennyyip** [comment]
thx
